version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pharmacie_db
    environment:
      POSTGRES_DB: pharmacie
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: pharmacie_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/pharmacie
      JWT_SECRET: pharmacare_secret_key_2025
      PORT: 5000
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: pharmacie_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: